feat: implement raw filed for web
capawesome-team/capacitor-file-picker pull request #34
Opened 2022-07-09 19:45 UTC by reslear

closes #25 

@robingenz is docs auto-generating?

2022-07-09 21:12 UTC, robingenz requested changes
Thank you! 2 minor changes requested.

2022-07-09 21:12 UTC, robingenz commented on src/definitions.ts
> +  files: FileModel[];
```suggestion
  files: FileResult[];
```

2022-07-09 21:12 UTC, robingenz commented on src/definitions.ts
> +   * The File instance
```suggestion
   * The File instance.
```

2022-07-09 21:12 UTC, robingenz commented
> closes #25
> 
> @robingenz is docs auto-generating?

No, please run `npm run docgen` and `npm run fmt`.

2022-07-09 22:10 UTC, reslear commented
@robingenz so, we change interface name, do we need changes for backward compatibility or use new version as major?

2022-07-10 11:36 UTC, robingenz commented
> @robingenz so, we change interface name, do we need changes for backward compatibility or use new version as major?

Next version will be `0.4.0` which means that the version contains breaking changes, as we are still in major version zero (0.y.z).

2022-07-13 18:25 UTC, robingenz commented
Hi @reslear,
I've reconsidered and decided that I don't want to release the next breaking changes until the update to Capacitor 4.
This plugin has received a lot of breaking changes and I would like to reduce that a bit.
For this reason I have created a new PR without breaking changes (see #37).
You can give it a try if you want:
```
npm i @robingenz/capacitor-file-picker@0.3.0-dev.d8fa252.1657736483
```

However, thank you for this PR! I hope that is fine for you.

2022-07-13 18:26 UTC, closed without merging